# Nome do site
site_name: "Passe Livre Estudantil"

# Descrição
site_description: "Repositório de documentos de Interação Humano-Computador"
repo_name: "2024.2-PasseLivreEstudantil"
repo_url: "https://github.com/Interacao-Humano-Computador/2024.2-PasseLivreEstudantil"

# Tema do MkDocs
theme:
  name: material
  features:
    - navigation.instant # Carrega páginas instantaneamente
    - navigation.tracking # Permite rastrear a navegação
    - navigation.tabs # Habilita abas de navegação no topo
    - navigation.tabs.sticky # Abas fixas na parte superior
    - navigation.top # Move o menu para o topo
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

  language: pt-BR
  favicon: assets/passeLivreEstudantilFavicon.png
  logo: assets/passeLivreEstudantil.png
  navigation:
    tabs: true

# Configura a navegação do site
nav:
  - Introdução: index.md
  - Reuniões:
      - Ata 1: atas/ata-1.md
      - Ata 2: atas/ata-2.md
      - Ata 3: atas/ata_3.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
      - Design: planejamento/design.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap: planejamento/heatmap.md
      - Sites avaliados: planejamento/sites_avaliados.md
      - Site escolhido: planejamento/sites_escolhidos.md
  - Apresentações:
      - Entrega 1: apresentacoes/entrega1/entrega1.md
      - Entrega 2: apresentacoes/entrega2/entrega2.md
      - Entrega 3: apresentacoes/entrega3/entrega3.md
      - Entrega 4: apresentacoes/entrega4/entrega4.md
      - Entrega 5: apresentacoes/entrega5/entrega5.md
  - Entrega Final:
      - Ciclo de vida: entrega-final/ciclo_de_vida.md
      - Cronograma Planejado e Executado: entrega-final/cronograma_planejado_e_executado.md
      - Execução do Projeto: entrega-final/execucao_do_projeto.md
      - Ferramentas Utilizadas: entrega-final/ferramentas_utilizadas.md
      - Resultados: entrega-final/resultados_alcancados.md
      - Site escolhido: entrega-final/site_escolhido.md
  - Verificação e Inspeção:
      - Grupo 7:
          - Entrega 01: verificacoes/grupo07/entrega01/verificacao_entrega01_grupo07.md
          - Entrega 02: verificacoes/grupo07/entrega02/verificacao_entrega02_grupo07.md
          - Entrega 03: verificacoes/grupo07/entrega03/verificacao_entrega03_grupo07.md
          - Entrega 04: verificacoes/grupo07/entrega04/verificacao_entrega04_grupo07.md
          - Entrega 06: 
            - Planejamento da verificação: verificacoes/grupo07/entrega06/Planejamento_da_verificacao.md
            - Planejamento da avaliação do Protótipo de papel: verificacoes/grupo07/entrega06/Planejamento_da_avaliação_do_prototipo_de_papel.md
            - Planejamento do relato dos resultados: verificacoes/grupo07/entrega06/Planejamento_do_relato_dos_resultados_do_prototipo_de_papel.md
            - Relato dos resultados do Protótipo de papel: verificacoes/grupo07/entrega06/Relato_dos_resultados_prototipo_de_papel.md
          - Entrega 07: 
            - Planejamento da verificação: verificacoes/grupo07/entrega07/Planejamento_da_verificacao.md
            - Planejamento da avaliação do Protótipo de alta fidelidade: verificacoes/grupo07/entrega07/Planejamento_da_avaliação_do_prototipo_de_alta_fidelidade.md
            - Planejamento do relato dos resultados: verificacoes/grupo07/entrega07/Planejamento_do_relato_dos_resultados.md
          - Verificacao Entrega Final:
            - Planejamento da Verificação Geral: verificacoes/grupo07/verificacao_geral/planejamento_da_verificacao_geral.md
            - Resultado da Verificação Geral: verificacoes/grupo07/verificacao_geral/resultado_verificacao_geral.md
            - Planejamento:
              - Cronograma: verificacoes/grupo07/verificacao_geral/planejamento/cronograma.md
              - Metodologia: verificacoes/grupo07/verificacao_geral/planejamento/metodologia.md
              - Design: verificacoes/grupo07/verificacao_geral/planejamento/design.md
              - Ferramentas: verificacoes/grupo07/verificacao_geral/planejamento/ferramentas.md
              - Heatmap: verificacoes/grupo07/verificacao_geral/planejamento/heatmap.md
              - Sites Avaliados: verificacoes/grupo07/verificacao_geral/planejamento/sites_avaliados.md
              - Site Escolhido: verificacoes/grupo07/verificacao_geral/planejamento/site_escolhido.md
            - Analise de Requisitos:
              - Aspectos Éticos: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/aspectos_eticos.md
              - Perfil de Usuário: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/perfil_de_usuario.md
              - Personas: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/personas.md
              - Cenários: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/cenarios.md
              - GOMS: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/GOMS.md
              - HTA: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/HTA.md
              - Princípios Gerais: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/principios_gerais.md
              - Metas de Usabilidade: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/metas_de_usabilidade.md
              - Guia de Estilo: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/guia_de_estilo.md
              - Caracteristicas Gerais: verificacoes/grupo07/verificacao_geral/analise_de_requisitos/caracteristicas_gerais.md
            - Design, Avaliação e Desenvolvimento:
              - Nivel 1:
                - Análise de Tarefas:
                  - Planejamento da Avaliacao da Análise de Tarefas: verificacoes/grupo07/verificacao_geral/nivel1/analise_de_tarefas/planejamento_da_avaliacao_da_analise_de_tarefas.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo07/verificacao_geral/nivel1/analise_de_tarefas/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo07/verificacao_geral/nivel1/analise_de_tarefas/relato_do_resultado.md
                - Storyboard:
                  - Planejamento da Avaliacao do Storyboard: verificacoes/grupo07/verificacao_geral/nivel1/storyboard/planejamento_da_avaliacao_do_storyboard.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo07/verificacao_geral/nivel1/storyboard/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo07/verificacao_geral/nivel1/storyboard/relato_do_resultado.md
                  - Storyboard: verificacoes/grupo07/verificacao_geral/nivel1/storyboard/storyboard.md
              - Nivel 2: 
                - Protótipo de Papel:
                  - Planejamento da Avaliacao do Protótipo de Papel: verificacoes/grupo07/verificacao_geral/nivel2/prototipo_de_papel/planejamento_da_avaliacao_do_prototipo_de_papel.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo07/verificacao_geral/nivel2/prototipo_de_papel/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo07/verificacao_geral/nivel2/prototipo_de_papel/relato_do_resultado.md
              - Nivel 3:
                - Protótipo de Alta Fidelidade:
                  - Planejamento da Avaliacao do Protótipo de Alta Fidelidade: verificacoes/grupo07/verificacao_geral/nivel3/prototipo_de_alta_fidelidade/planejamento_da_avaliacao_do_prototipo_de_alta_fidelidade.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo07/verificacao_geral/nivel3/prototipo_de_alta_fidelidade/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo07/verificacao_geral/nivel3/prototipo_de_alta_fidelidade/relato_do_resultado.md
   


      - Grupo 8:
          - Entrega 01: verificacoes/grupo08/entrega01/verificacao_entrega01_grupo08.md
          - Entrega 02: verificacoes/grupo08/entrega02/verificacao_entrega02_grupo08.md
          - Entrega 03: verificacoes/grupo08/entrega03/verificacao_entrega_03_grupo08.md
          - Entrega 04: verificacoes/grupo08/entrega04/verificacao_entrega04_grupo08.md
          - Verificacao Entrega Final:
            - Planejamento da Verificação Geral: verificacoes/grupo08/verificacao_geral/planejamento_da_verificacao_geral.md
            - Planejamento:
              - Cronograma: verificacoes/grupo08/verificacao_geral/planejamento/cronograma.md
              - Metodologia: verificacoes/grupo08/verificacao_geral/planejamento/metodologia.md
              - Design: verificacoes/grupo08/verificacao_geral/planejamento/design.md
              - Ferramentas: verificacoes/grupo08/verificacao_geral/planejamento/ferramentas.md
              - Heatmap: verificacoes/grupo08/verificacao_geral/planejamento/heatmap.md
              - Sites Avaliados: verificacoes/grupo08/verificacao_geral/planejamento/sites_avaliados.md
              - Site Escolhido: verificacoes/grupo08/verificacao_geral/planejamento/site_escolhido.md
            - Analise de Requisitos:
              - Aspectos Éticos: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/aspectos_eticos.md
              - Perfil de Usuário: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/perfil_de_usuario.md
              - Personas: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/personas.md
              - Cenários: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/cenarios.md
              - GOMS: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/GOMS.md
              - HTA: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/HTA.md
              - Metas de Usabilidade: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/metas_de_usabilidade.md
              - Guia de Estilo: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/guia_de_estilo.md
              - Caracteristicas Gerais: verificacoes/grupo08/verificacao_geral/analise_de_requisitos/caracteristicas_gerais.md
            - Design, Avaliação e Desenvolvimento:
              - Nivel 1:
                - Análise de Tarefas:
                  - Planejamento da Avaliacao da Análise de Tarefas: verificacoes/grupo08/verificacao_geral/nivel1/analise_de_tarefas/planejamento_da_avaliacao_da_analise_de_tarefas.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo08/verificacao_geral/nivel1/analise_de_tarefas/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo08/verificacao_geral/nivel1/analise_de_tarefas/relato_do_resultado.md
                - Storyboard:
                  - Planejamento da Avaliacao do Storyboard: verificacoes/grupo08/verificacao_geral/nivel1/storyboard/planejamento_da_avaliacao_do_storyboard.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo08/verificacao_geral/nivel1/storyboard/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo08/verificacao_geral/nivel1/storyboard/relato_do_resultado.md
                  - Storyboard: verificacoes/grupo08/verificacao_geral/nivel1/storyboard/storyboard.md
              - Nivel 2: 
                - Protótipo de Papel:
                  - Planejamento da Avaliacao do Protótipo de Papel: verificacoes/grupo08/verificacao_geral/nivel2/prototipo_de_papel/planejamento_da_avaliacao_do_prototipo_de_papel.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo08/verificacao_geral/nivel2/prototipo_de_papel/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo08/verificacao_geral/nivel2/prototipo_de_papel/relato_do_resultado.md
              - Nivel 3:
                - Protótipo de Alta Fidelidade:
                  - Planejamento da Avaliacao do Protótipo de Alta Fidelidade: verificacoes/grupo08/verificacao_geral/nivel3/prototipo_de_alta_fidelidade/planejamento_da_avaliacao_do_prototipo_de_alta_fidelidade.md
                  - Planejamento do Relato dos Resultados: verificacoes/grupo08/verificacao_geral/nivel3/prototipo_de_alta_fidelidade/planejamento_do_relato_dos_resultados.md
                  - Relato do Resultado: verificacoes/grupo08/verificacao_geral/nivel3/prototipo_de_alta_fidelidade/relato_do_resultado.md

  - Análise de Requisitos:
      - Aspectos Éticos: analise_de_requsitos/aspectos_eticos.md
      - Perfil de Usuário: analise_de_requsitos/perfil_de_usuario.md
      - Personas: analise_de_requsitos/personas.md
      - Cenários: analise_de_requsitos/cenarios.md
      - Análise de Tarefas:
          - GOMS: analise_de_requsitos/analise_tarefas/goms.md
          - HTA: analise_de_requsitos/analise_tarefas/hta.md
      - Termo de Consentimento: analise_de_requsitos/termo_de_consentimento.md
      - Princípios Gerais: analise_de_requsitos/principios_gerais.md
      - Metas de Usabilidade: analise_de_requsitos/metas_de_usabilidade.md
      - Guia de estilo: analise_de_requsitos/guia_de_estilo.md
      - Caracteristicas Gerais: analise_de_requsitos/caracteristicas.md
  - Design, Avaliação e Desenvolvimento:
      - Nivel 1:
          - Análise de Tarefas:
              - Planejamento da Avaliacao da Análise de Tarefas: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados da Avaliacao: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/planejamento_relato_resultados_avaliacao.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel01/analise_de_tarefas/relato_resultado.md
          - Storyboard:
              - Planejamento da Avaliacao do Storyboard: design_avaliacao_desenvolvimento/nivel01/storyboard/planejamento_avaliacao.md
              - Planejamento do Relato dos Resultados: design_avaliacao_desenvolvimento/nivel01/storyboard/planejamento_relato_resultados_avaliacao.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel01/storyboard/relato_resultado.md
              - Storyboards: design_avaliacao_desenvolvimento/nivel01/storyboard/storyboards.md
      - Nivel 2:
          - Protótipo de papel:
              - Planejamento da Avaliacao do Protótipo de Papel: design_avaliacao_desenvolvimento/nivel02/planejamento_avaliacao_prototipo_papel.md
              - Planejamento do Relato dos Resultados: design_avaliacao_desenvolvimento/nivel02/planejamento_relato_prototipo_papel.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel02/relato_resultado_prototipo_papel.md
              # - Protótipos de Papel: design_avaliacao_desenvolvimento/nivel02/prototipos_papel.md
      - Nivel 3:
          - Protótipo de Alta Fidelidade:
              - Planejamento da Avaliacao do Protótipo de Alta Fidelidade: design_avaliacao_desenvolvimento/nivel03/planejamento_da_avaliacao_do_prototipo_de_alta_fidelidade.md
              - Planejamento do Relato dos Resultados: design_avaliacao_desenvolvimento/nivel03/planejamento_do_relato_dos_resultados.md
              - Relato do Resultado: design_avaliacao_desenvolvimento/nivel03/relato_resultado_prototipo_alta_fidelidade.md
              # - Protótipos de Alta Fidelidade: design_avaliacao_desenvolvimento/nivel03/prototipos_alta_fidelidade.md
extra:
  version:
    provider: mike
